const en = {
    'home': 'Home',
    'aboutCompany': 'About company',
    'products': 'Products',
    'contacts': 'Contacts',
    'constructionAnd': 'construction and manufacturing company',
    'weOffer': 'We offer our customers standardized metal products for greenhouses, gazebos, outbuildings, sheds, garages, warehouses and commercial premises, as well as products for individual projects.',
    'action': 'Action',
    'upTo': 'Up to 50% discount until 1.09.22. For all metal structures!!!',
    'ourProduction': 'Our production',
    'benefits': 'Benefits',
    'mountingSpeed': 'Mounting speed',
    'productionOfWorks': 'Production of works at any time of the year.',
    'lowCost': 'Low cost',
    'noProductionWaste': 'No production waste, no need to dispose of leftovers. Custom designs, superstructures and extensions are possible.',
    'easeOfInstallation': 'Ease of installation',
    'doesNotRequire': 'Does not require the involvement of additional equipment for installation. Possibility of self-assembly.',
    'durability': 'Durability',
    'noAdditional': 'No additional protection is required, unlike wooden frame houses.',
    'askTheQuestion': 'Ask a question to the manager',
    'send': 'Send',
    'ordersPerMonth': 'Orders per month',
    'ordersPerYear': 'Orders per year',
    'isEnActively': 'LLC "RUVAL-Project" is an actively developing young company that specializes in industrial construction projects. The range of services provided begins with the preparation of the foundation pit and ends with the final improvement and landscaping of the adjacent territory.',
    'hasAWell': 'LLC "RUVAL-Project" has a well-established clear system of management and control of production and supply processes both on the territory of the Republic of Belarus and on the territory of the Russian Federation, which allows minimizing costs and offering a competitive price to Customers. A well-established structure greatly simplifies interaction and increases efficiency when working at facilities under construction, allowing you to significantly reduce the cost and time of construction and installation work.',
    'ourSpecialists': 'Our specialists are ready to deliver the structures in a quality and timely manner, and then assemble them on a turnkey basis, right at your construction site.',
    'toLearnMore': 'To learn more',
    'connectWithUs': 'Connect with us',
    'republicOfBelarus': 'Republic of Belarus 220099, Minsk, st. Kazinets,',
    'room': '11a, room 112a',
    'limitedLiability': 'Limited Liability Company "Ruval-Project"',
    'republicOfBelarusMinsk': 'Republic of Belarus, Minsk, st. Kazintsa, 11a, room. 112a.',    
}